name: exception_hiding_lint
description: Custom lint rules to prevent exception hiding patterns in Dart code.
version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^6.8.0
  custom_lint_builder: ^0.6.7

dev_dependencies:
  custom_lint: ^0.6.7
  lints: ^4.0.0
  test: ^1.21.0
